// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /*static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmTF-Pxypoqk3y5VWdzFz1W6xwsGL5JWQ',
    appId: '1:858845123746:web:2128f923aa100a0b18b3fb',
    messagingSenderId: '858845123746',
    projectId: 'sx-s4c',
    authDomain: 'sx-s4c.firebaseapp.com',
    storageBucket: 'sx-s4c.appspot.com',
    measurementId: 'G-RHF59G1XVK',
  );*/
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXSDWwK4F0cMn2qX_qHTobAnycUQVZrYs',
    appId: '1:43058865463:web:1a621cb3f19d9fa6e826b2',
    messagingSenderId: '43058865463',
    projectId: 'worket-375fc',
    authDomain: 'worket-375fc.firebaseapp.com',
    storageBucket: 'worket-375fc.appspot.com',
    measurementId: 'G-S69TBJ4CWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkh1zNb-yvCTPbSkduSLMBJpBHDIeuQEU',
    appId: '1:858845123746:android:f297f895263e468818b3fb',
    messagingSenderId: '858845123746',
    projectId: 'sx-s4c',
    storageBucket: 'sx-s4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3W7iNEtSPu2OxHZ565QIFBPs03Fs8aLs',
    appId: '1:858845123746:ios:82d67f226924550918b3fb',
    messagingSenderId: '858845123746',
    projectId: 'sx-s4c',
    storageBucket: 'sx-s4c.appspot.com',
    iosClientId:
        '858845123746-e4gkid9g695ujbelgept8lsr20t1vi71.apps.googleusercontent.com',
    iosBundleId: 'com.shidix.sic4change',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3W7iNEtSPu2OxHZ565QIFBPs03Fs8aLs',
    appId: '1:858845123746:ios:033ecef942c50e0318b3fb',
    messagingSenderId: '858845123746',
    projectId: 'sx-s4c',
    storageBucket: 'sx-s4c.appspot.com',
    iosClientId:
        '858845123746-d9ds4agpkvrfa50foc1a7a7dhic82tfn.apps.googleusercontent.com',
    iosBundleId: 'com.shidix.sic4change.RunnerTests',
  );
}
